/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as SuperRouteImport } from './routes/super'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as MenuSlugRouteImport } from './routes/menu.$slug'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as SuperSplatRouteImport } from './routes/super.$'
import { Route as RSlugAdminRouteImport } from './routes/r.$slug.admin'
import { Route as RSlugAdminIndexRouteImport } from './routes/r.$slug.admin.index'
import { Route as RSlugAdminSplatRouteImport } from './routes/r.$slug.admin.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const MenuSlugRoute = MenuSlugRouteImport.update({
  id: '/menu/$slug',
  path: '/menu/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSplatRoute = SuperSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SuperRoute,
} as any)
const RSlugAdminRoute = RSlugAdminRouteImport.update({
  id: '/r/$slug/admin',
  path: '/r/$slug/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugAdminIndexRoute = RSlugAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RSlugAdminRoute,
} as any)
const RSlugAdminSplatRoute = RSlugAdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => RSlugAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/preview': typeof PreviewRoute
  '/super': typeof SuperRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/super/$': typeof SuperSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
  '/r/$slug/admin': typeof RSlugAdminRouteWithChildren
  '/r/$slug/admin/$': typeof RSlugAdminSplatRoute
  '/r/$slug/admin/': typeof RSlugAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/admin/$': typeof AdminSplatRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/super/$': typeof SuperSplatRoute
  '/admin': typeof AdminIndexRoute
  '/super': typeof SuperIndexRoute
  '/r/$slug/admin/$': typeof RSlugAdminSplatRoute
  '/r/$slug/admin': typeof RSlugAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/preview': typeof PreviewRoute
  '/super': typeof SuperRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/super/$': typeof SuperSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
  '/r/$slug/admin': typeof RSlugAdminRouteWithChildren
  '/r/$slug/admin/$': typeof RSlugAdminSplatRoute
  '/r/$slug/admin/': typeof RSlugAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/preview'
    | '/super'
    | '/admin/$'
    | '/menu/$slug'
    | '/super/$'
    | '/admin/'
    | '/super/'
    | '/r/$slug/admin'
    | '/r/$slug/admin/$'
    | '/r/$slug/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview'
    | '/admin/$'
    | '/menu/$slug'
    | '/super/$'
    | '/admin'
    | '/super'
    | '/r/$slug/admin/$'
    | '/r/$slug/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/preview'
    | '/super'
    | '/admin/$'
    | '/menu/$slug'
    | '/super/$'
    | '/admin/'
    | '/super/'
    | '/r/$slug/admin'
    | '/r/$slug/admin/$'
    | '/r/$slug/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PreviewRoute: typeof PreviewRoute
  SuperRoute: typeof SuperRouteWithChildren
  MenuSlugRoute: typeof MenuSlugRoute
  RSlugAdminRoute: typeof RSlugAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/menu/$slug': {
      id: '/menu/$slug'
      path: '/menu/$slug'
      fullPath: '/menu/$slug'
      preLoaderRoute: typeof MenuSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/$': {
      id: '/super/$'
      path: '/$'
      fullPath: '/super/$'
      preLoaderRoute: typeof SuperSplatRouteImport
      parentRoute: typeof SuperRoute
    }
    '/r/$slug/admin': {
      id: '/r/$slug/admin'
      path: '/r/$slug/admin'
      fullPath: '/r/$slug/admin'
      preLoaderRoute: typeof RSlugAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug/admin/': {
      id: '/r/$slug/admin/'
      path: '/'
      fullPath: '/r/$slug/admin/'
      preLoaderRoute: typeof RSlugAdminIndexRouteImport
      parentRoute: typeof RSlugAdminRoute
    }
    '/r/$slug/admin/$': {
      id: '/r/$slug/admin/$'
      path: '/$'
      fullPath: '/r/$slug/admin/$'
      preLoaderRoute: typeof RSlugAdminSplatRouteImport
      parentRoute: typeof RSlugAdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperRouteChildren {
  SuperSplatRoute: typeof SuperSplatRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperSplatRoute: SuperSplatRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

interface RSlugAdminRouteChildren {
  RSlugAdminSplatRoute: typeof RSlugAdminSplatRoute
  RSlugAdminIndexRoute: typeof RSlugAdminIndexRoute
}

const RSlugAdminRouteChildren: RSlugAdminRouteChildren = {
  RSlugAdminSplatRoute: RSlugAdminSplatRoute,
  RSlugAdminIndexRoute: RSlugAdminIndexRoute,
}

const RSlugAdminRouteWithChildren = RSlugAdminRoute._addFileChildren(
  RSlugAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PreviewRoute: PreviewRoute,
  SuperRoute: SuperRouteWithChildren,
  MenuSlugRoute: MenuSlugRoute,
  RSlugAdminRoute: RSlugAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
